version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:  
      - npm install
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 056665234171.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker-compose --file=docker-compose-prod.yml build
      #- docker-compose --file=docker-compose-prod.yml build --no-cache
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker-compose --file=docker-compose-prod.yml push
artifacts:
  files:
    - 'Dockerrun.aws.json'
